apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-config-pvc
  
  labels:
    project: data
spec:
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes-1
  accessModes:
    # - ReadOnlyMany
    # - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 32Mi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fb-db-pvc
  
  labels:
    project: data
    
spec:
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes-1
  accessModes:
    # - ReadOnlyMany
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fb-conf-pvc
  
  labels:
    project: data
    
spec:
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes-1
  accessModes:
    # - ReadOnlyMany
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: 128Mi

