apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: matrix-landing-page-autoscaler
  labels:
    matrix-service: webclient
    scaleThing: matrix-webpage
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matrix-landing-page-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
